FROM python:3.7-slim-stretch AS sls-fastapi-build

## create requirements files
COPY ./Pipfile /Pipfile
RUN pip install pipenv \
    && pipenv lock -r > requirements.txt \
    && pipenv lock -r --dev > requirements-dev.txt

#### create deployment image
FROM python:3.7-slim-stretch AS sls-fastapi

# create a user
RUN useradd app && mkdir /home/app \
    && chown app:app /home/app
RUN apt-get update && apt-get install -y gcc
COPY --from=sls-fastapi-build /requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

USER app
WORKDIR /home/app

ENTRYPOINT ["uvicorn"]
CMD ["main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

#### create development image
FROM python:3.7-slim-stretch AS sls-fastapi-dev

# create a user
RUN useradd app && mkdir /home/app \
    && chown app:app /home/app
RUN apt-get update && apt-get install -y gcc
COPY --from=sls-fastapi-build /requirements-dev.txt /requirements.txt
RUN pip install -r /requirements.txt

USER app
WORKDIR /home/app

ENTRYPOINT ["uvicorn"]
CMD ["main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
