---
Description: DynamoDB table for simple todo
Resources:
  DynamodbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: simple-todo
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
        - AttributeName: created_at
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
